# Generated by Django 3.2.3 on 2022-02-12 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Estación',
                'verbose_name_plural': '01 - Estaciones',
            },
        ),
        migrations.CreateModel(
            name='InformeVariableMeteorologicaGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnico', models.CharField(max_length=255, verbose_name='Técnico')),
                ('temperatura', models.FloatField()),
                ('viento', models.FloatField()),
                ('lluvia', models.FloatField()),
                ('humedad', models.IntegerField()),
                ('barometro', models.IntegerField()),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y hora')),
            ],
            options={
                'verbose_name': 'Informe de variable meteorológica general',
                'verbose_name_plural': '04 - Informes de variables meteorólogicas generales',
            },
        ),
        migrations.CreateModel(
            name='ParteMeteorologicoGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnico', models.CharField(max_length=255, verbose_name='Técnico')),
                ('temperatura', models.FloatField()),
                ('viento', models.FloatField()),
                ('lluvia', models.FloatField()),
            ],
            options={
                'verbose_name': 'Parte meteorológico general',
                'verbose_name_plural': '05 - Partes meteorológicos generales',
            },
        ),
        migrations.CreateModel(
            name='ParteMeteorologicoProvincial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meteorologo', models.CharField(max_length=255, verbose_name='Meteorólogo')),
                ('provincia', models.CharField(choices=[('1', 'Pinar del Río'), ('2', 'La Habana'), ('3', 'Artemisa'), ('4', 'Mayabeque'), ('5', 'Matanzas'), ('6', 'Villa Clara'), ('7', 'Cienfuegos'), ('8', 'Sancti Spíritus'), ('9', 'Ciego de Avila'), ('10', 'Camaguey'), ('11', 'Las Tunas'), ('12', 'Holguín'), ('13', 'Granma'), ('14', 'Santiago de Cuba'), ('15', 'Guantánamo'), ('16', 'Isla de la Juventud')], max_length=255)),
                ('temperatura', models.FloatField()),
                ('viento', models.FloatField()),
                ('lluvia', models.FloatField()),
            ],
            options={
                'verbose_name': 'Parte meteorológico provincial',
                'verbose_name_plural': '05 - Partes meteorológicos provinciales',
            },
        ),
        migrations.CreateModel(
            name='ReporteVariableMeteorologica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meteorologo', models.CharField(max_length=255, verbose_name='Meteorólogo')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y hora')),
                ('dirr', models.FloatField(verbose_name='DIRR')),
                ('dirs', models.FloatField(verbose_name='DIRS')),
                ('vels', models.FloatField(verbose_name='VELS')),
                ('velp', models.FloatField(verbose_name='VELP')),
                ('temperatura', models.FloatField()),
                ('humedad', models.IntegerField()),
                ('presion', models.IntegerField()),
                ('estacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.estacion')),
            ],
            options={
                'verbose_name': 'Reporte de variable meteorológica',
                'verbose_name_plural': '02 - Reportes de variables meteorólogicas',
            },
        ),
        migrations.CreateModel(
            name='InformeOficialVariableMeteorologicaPronvincial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(choices=[('1', 'Pinar del Río'), ('2', 'La Habana'), ('3', 'Artemisa'), ('4', 'Mayabeque'), ('5', 'Matanzas'), ('6', 'Villa Clara'), ('7', 'Cienfuegos'), ('8', 'Sancti Spíritus'), ('9', 'Ciego de Avila'), ('10', 'Camaguey'), ('11', 'Las Tunas'), ('12', 'Holguín'), ('13', 'Granma'), ('14', 'Santiago de Cuba'), ('15', 'Guantánamo'), ('16', 'Isla de la Juventud')], max_length=255)),
                ('tecnico', models.CharField(max_length=255, verbose_name='Técnico')),
                ('temperatura', models.FloatField()),
                ('viento', models.FloatField()),
                ('lluvia', models.FloatField()),
                ('humedad', models.IntegerField()),
                ('barometro', models.IntegerField()),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y hora')),
                ('estacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.estacion')),
            ],
            options={
                'verbose_name': 'Informe oficial de variable meteorológica provincial',
                'verbose_name_plural': '03 - Informes oficiales de variables meteorólogicas provinciales',
            },
        ),
    ]
