# Generated by Django 3.2.3 on 2022-02-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partemeteorologicogeneral',
            options={'verbose_name': 'Parte meteorológico general', 'verbose_name_plural': '06 - Partes meteorológicos generales'},
        ),
        migrations.AddField(
            model_name='partemeteorologicogeneral',
            name='fecha_hora',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha y hora'),
        ),
        migrations.AddField(
            model_name='partemeteorologicoprovincial',
            name='fecha_hora',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha y hora'),
        ),
        migrations.AlterField(
            model_name='informeoficialvariablemeteorologicapronvincial',
            name='fecha_hora',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha y hora'),
        ),
        migrations.AlterField(
            model_name='informevariablemeteorologicageneral',
            name='fecha_hora',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha y hora'),
        ),
        migrations.AlterField(
            model_name='reportevariablemeteorologica',
            name='fecha_hora',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha y hora'),
        ),
    ]
