# Generated by Django 3.2.3 on 2022-02-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20220212_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informeoficialvariablemeteorologicapronvincial',
            name='fecha_hora',
            field=models.DateTimeField(verbose_name='Fecha y hora'),
        ),
        migrations.AlterField(
            model_name='informevariablemeteorologicageneral',
            name='fecha_hora',
            field=models.DateTimeField(verbose_name='Fecha y hora'),
        ),
        migrations.AlterField(
            model_name='partemeteorologicogeneral',
            name='fecha_hora',
            field=models.DateTimeField(verbose_name='Fecha y hora'),
        ),
        migrations.AlterField(
            model_name='partemeteorologicoprovincial',
            name='fecha_hora',
            field=models.DateTimeField(verbose_name='Fecha y hora'),
        ),
        migrations.AlterField(
            model_name='reportevariablemeteorologica',
            name='fecha_hora',
            field=models.DateTimeField(verbose_name='Fecha y hora'),
        ),
    ]
